docs: Add how-to for WSOA
siderolabs/omni-docs pull request #79
Opened 2024-05-07 13:25 UTC by MAHDTech

This PR adds a how-to guide for configuring VMware Workspace ONE Access with SAML for Omni.

2024-05-08 09:41 UTC, TimJones requested changes
Many thanks for the contribution!

Can you add a text-based descriptions rather than just an images? Like with the table on the first configuration options image.  
It's much better for people who need screen-readers or have other visual impairments.

2024-05-08 09:41 UTC, TimJones commented on content/docs/how-to-guides/how-to-configure-saml-wsoa/_index.md
> +
```suggestion
```
This can be dropped as the `description` is already output and says essentially the same thing.

2024-05-08 09:41 UTC, TimJones commented on content/docs/how-to-guides/how-to-configure-saml-wsoa/_index.md
> +Now Enter a Name, Description and select an Icon before clicking on _Next_.
```suggestion
Now enter a name, description, and select an icon before clicking on _Next_.
```

2024-05-08 10:36 UTC, MAHDTech commented
No problem, happy to help.

I've made the suggested changes and improved the formatting a little, let me know if you need further changes.

2024-05-08 12:46 UTC, Unix4ever commented
Let's also add a link to this SAML provider in this list https://github.com/siderolabs/omni-docs/blob/34d82da7fc6ecad30101e614121fcb25d7878ffc/content/docs/how-to-guides/how-to-deploy-omni-on-prem/index.md?plain=1#L81

2024-05-10 10:33 UTC, MAHDTech commented
Apologies for the delay, I've added the missing link and I also renamed the folder match the naming convention from the others.

Cheers 🍻

2024-05-14 10:19 UTC, MAHDTech commented
You can hold on this on this one until siderolabs/omni#232 is in and then I will update the docs based on any changes there as it's related.

Thanks all :+1:

2024-05-20 14:08 UTC, TimJones commented
@MAHDTech Thanks for the contribution! If you could squash your commits down to one, I'll sign that and merge it!

2024-06-04 10:41 UTC, TimJones approved these changes

2024-06-04 10:41 UTC, TimJones commented
/m

2024-06-04 10:42 UTC, merged